### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Enet4**
I took the liberty of updating `ureq` to 2.4 and `sha2` to 0.10.

### CODE REVIEW

**Review by robyoung — APPROVED** [review]

**Comment by Enet4** [comment]
Hello @robyoung! Once you have an open window, a crate release at crates.io of pending changes would be much appreciated. :pray:

**Comment by robyoung** [comment]
Sorry about the delay @Enet4 I have now uploaded that.

I don't do much with this anymore. Would you be interested in taking over the project or me adding you as a maintainer. It's totally fine if not, it's just if you depend on it you would be able to get changes in quicker.

**Comment by Enet4** [comment]
Thank you for the invitation, @robyoung. For now, I would be glad to be added as a repository collaborator and additional crate owner, mostly for redundancy. Later on, we can see whether I should take up a more proactive role.

**Comment by Enet4** [comment]
Hello again @robyoung! I have been taking the liberty of extending the project with some extra features and data sets, but I feel that we would both be more comfortable with the crate becoming part of DICOM-rs in a more official manner. For this, would it be OK for you to have a repository ownership transfer to me?

**Pull request merged**
